//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VACUN_ARG2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VACUN_ARG2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar {
            get {
                object obj = ResourceManager.GetObject("buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;54&quot;: [{&quot;id&quot;: &quot;54028&quot;, &quot;nombre&quot;: &quot;Capital&quot;}, {&quot;id&quot;: &quot;54063&quot;, &quot;nombre&quot;: &quot;Iguazú&quot;}, {&quot;id&quot;: &quot;54091&quot;, &quot;nombre&quot;: &quot;Oberá&quot;}, {&quot;id&quot;: &quot;54098&quot;, &quot;nombre&quot;: &quot;San Ignacio&quot;}, {&quot;id&quot;: &quot;54035&quot;, &quot;nombre&quot;: &quot;Concepción&quot;}, {&quot;id&quot;: &quot;54119&quot;, &quot;nombre&quot;: &quot;25 de Mayo&quot;}, {&quot;id&quot;: &quot;54105&quot;, &quot;nombre&quot;: &quot;San Javier&quot;}, {&quot;id&quot;: &quot;54007&quot;, &quot;nombre&quot;: &quot;Apóstoles&quot;}, {&quot;id&quot;: &quot;54042&quot;, &quot;nombre&quot;: &quot;Eldorado&quot;}, {&quot;id&quot;: &quot;54112&quot;, &quot;nombre&quot;: &quot;San Pedro&quot;}, {&quot;id&quot;: &quot;54084&quot;, &quot;nombre&quot;: &quot;Montecarlo&quot;}, {&quot;id&quot;: &quot;54021&quot;, &quot;nombre&quot;: &quot;Candelaria&quot;}, {&quot;id&quot;: &quot;54014&quot;, &quot;nomb....
        /// </summary>
        internal static string departamentos_mod {
            get {
                return ResourceManager.GetString("departamentos_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;54&quot;: [{&quot;id&quot;: &quot;54007010000&quot;, &quot;nombre&quot;: &quot;APOSTOLES&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007020000&quot;, &quot;nombre&quot;: &quot;AZARA&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007025000&quot;, &quot;nombre&quot;: &quot;BARRIO RURAL&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007030000&quot;, &quot;nombre&quot;: &quot;ESTACION APOSTOLES&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007040000&quot;, &quot;nombre&quot;: &quot;PINDAPOY&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007050000&quot;, &quot;nombre&quot;: &quot;RINCON DE AZARA&quot;, &quot;id_departamento&quot;: &quot;54007&quot;}, {&quot;id&quot;: &quot;54007060000&quot;, &quot;nombre&quot;: &quot;SAN JOSE&quot;, &quot;id [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string localidades_mod {
            get {
                return ResourceManager.GetString("localidades_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;countries&quot;: [
        ///      {
        ///        &quot;name_en&quot;: &quot;Afghanistan&quot;,
        ///        &quot;name_es&quot;: &quot;Afganistán&quot;,
        ///        &quot;dial_code&quot;: &quot;+93&quot;,
        ///        &quot;code&quot;: &quot;AF&quot;
        ///      },
        ///      {
        ///        &quot;name_en&quot;: &quot;Albania&quot;,
        ///        &quot;name_es&quot;: &quot;Albania&quot;,
        ///        &quot;dial_code&quot;: &quot;+355&quot;,
        ///        &quot;code&quot;: &quot;AL&quot;
        ///      },
        ///      {
        ///        &quot;name_en&quot;: &quot;Algeria&quot;,
        ///        &quot;name_es&quot;: &quot;Argelia&quot;,
        ///        &quot;dial_code&quot;: &quot;+213&quot;,
        ///        &quot;code&quot;: &quot;DZ&quot;
        ///      },
        ///      {
        ///        &quot;name_en&quot;: &quot;AmericanSamoa&quot;,
        ///        &quot;name_es&quot;: &quot;Samoa Americana&quot;,        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string paises {
            get {
                return ResourceManager.GetString("paises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;54&quot;: &quot;Misiones&quot;, &quot;74&quot;: &quot;San Luis&quot;, &quot;70&quot;: &quot;San Juan&quot;, &quot;30&quot;: &quot;Entre Ríos&quot;, &quot;78&quot;: &quot;Santa Cruz&quot;, &quot;62&quot;: &quot;Río Negro&quot;, &quot;26&quot;: &quot;Chubut&quot;, &quot;14&quot;: &quot;Córdoba&quot;, &quot;50&quot;: &quot;Mendoza&quot;, &quot;46&quot;: &quot;La Rioja&quot;, &quot;10&quot;: &quot;Catamarca&quot;, &quot;42&quot;: &quot;La Pampa&quot;, &quot;86&quot;: &quot;Santiago del Estero&quot;, &quot;18&quot;: &quot;Corrientes&quot;, &quot;82&quot;: &quot;Santa Fe&quot;, &quot;90&quot;: &quot;Tucumán&quot;, &quot;58&quot;: &quot;Neuquén&quot;, &quot;66&quot;: &quot;Salta&quot;, &quot;22&quot;: &quot;Chaco&quot;, &quot;34&quot;: &quot;Formosa&quot;, &quot;38&quot;: &quot;Jujuy&quot;, &quot;02&quot;: &quot;Ciudad Autónoma de Buenos Aires&quot;, &quot;06&quot;: &quot;Buenos Aires&quot;, &quot;94&quot;: &quot;Tierra del Fuego, Antártida e Islas del Atlántico Sur&quot;}.
        /// </summary>
        internal static string provincias_mod {
            get {
                return ResourceManager.GetString("provincias_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vacuna {
            get {
                object obj = ResourceManager.GetObject("vacuna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
